apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    creationTimestamp: 2018-12-12T08:25:45Z
    generation: 1
    labels:
      app: dex
      chart: dex-1.0.0
      env: dev
      heritage: Tiller
      release: eerie-prawn
    name: eerie-prawn-dex
    namespace: default
    resourceVersion: "1587"
    selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/eerie-prawn-dex
    uid: 85781253-fde7-11e8-8e75-702bb32bc8e5
  spec:
    rules:
    - host: dex.minikube.test
      http:
        paths:
        - backend:
            serviceName: eerie-prawn-dex
            servicePort: 5556
          path: /
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.122.205
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    creationTimestamp: 2018-12-12T08:27:36Z
    generation: 1
    labels:
      app: dex-k8s-authenticator
      chart: dex-k8s-authenticator-1.0.0
      env: dev
      heritage: Tiller
      release: wobbly-greyhound
    name: wobbly-greyhound-dex-k8s-authenticator
    namespace: default
    resourceVersion: "1586"
    selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/wobbly-greyhound-dex-k8s-authenticator
    uid: c7d4ad02-fde7-11e8-8e75-702bb32bc8e5
  spec:
    rules:
    - host: dexauth.minikube.test
      http:
        paths:
        - backend:
            serviceName: wobbly-greyhound-dex-k8s-authenticator
            servicePort: 5555
          path: /
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.122.205
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
