apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.fullname" . }}
    env: {{ default "dev" .Values.global.deployEnv }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- range $key, $value := .Values.envSecrets }}
  {{ template "dex.envkey" $key }}: "{{ $value | b64enc }}"
  {{- end }}
